application: cskud-main
version: 1
runtime: python27
api_version: 1
threadsafe: no
handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /css
  static_dir: css

- url: /proto/css
  static_dir: proto/css

- url: /proto/js
  static_dir: proto/js

- url: /img
  static_dir: img

- url: /impress
  static_dir: impress

- url: .*
  script: main.py